# all predicates : owl:ObjectProperty : label


PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select * 
    where { 
        { GRAPH <https://osgeo.geolexica.org/api/concepts/6/> {?s ?p ?o ;
                        a skos:Concept.                                        } }
    }