# all resources : "abbreviation"@en
# remove language datatype/tag if not indicated in resource. 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX osgeo: <https://osgeo.geolexica.org/api/geolexica#>

select ?resource ?prefLabel
    where { 
        ?resource a skos:Concept ; osgeo:abbreviation "SOAP" ; skos:prefLabel ?prefLabel .
    }