#  all resources : label : japanese


PREFIX osgeo: <https://osgeo.geolexica.org/api/geolexica#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX lang: <https://osgeo.geolexica.org/api/language#>

select ?resource ?label 
        where { 
   
            { GRAPH <https://osgeo.geolexica.org/api/concepts#> {
                ?resource osgeo:hasLangCode lang:jpn ;
                   rdfs:label ?label . } }
    		}