# all sources : labels :uri


PREFIX osgeo: <https://osgeo.geolexica.org/api/geolexica#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

select ?source ?label ?title ?uri

where { 
    ?source a osgeo:Source ; rdfs:label ?label ; dcterms:title ?title .
     OPTIONAL { ?source dcterms:source ?uri }
    } ORDER BY ?uri