## all concepts : id : label : note : asc
 
PREFIX osgeo: <https://osgeo.geolexica.org/api/geolexica#>
PREFIX osgeo-lang: <https://osgeo.geolexica.org/api/osgeo-lang#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?label ?note  

		{ { GRAPH <https://osgeo.geolexica.org/api/osgeo-concept/> 
                {?concept a skos:Concept ; osgeo-lang:eng-note ?note ;
				rdfs:label ?label  .            
        } } 
    } ORDER BY ?label