# one concept : all resources : dcterms:identifier 12

PREFIX dcterms: <http://purl.org/dc/terms/>

select ?predicate ?object

    where { 
        { GRAPH <https://osgeo.geolexica.org/api/concepts#> 
                {?s ?predicate ?object ; dcterms:identifier 12.              
        } }
    }