# all resources : "abbreviation"@en
# remove language datatype/tag if not indicated in resource. 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select ?resource ?prefLabel
    where { 
        ?resource a skos:Concept ; rdfs:label "abbreviation" ; skos:prefLabel ?prefLabel .
    }