# all predicates : owl:ObjectProperty : label


PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select DISTINCT ?predicate ?label

    where {
        ?predicate a owl:ObjectProperty ;
                   rdfs:label ?label .
    }