## Count total # of sources.
 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX geolexica: <https://isotc211.geolexica.org/api/geolexica#>

SELECT (COUNT(?source) AS ?source_count)

WHERE
{ ?source a geolexica:Source .
}