# all concepts : label : dcterms:identifier : descending


PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label ?id ?term
    WHERE {
        ?term a skos:Concept ; dcterms:identifier ?id ; rdfs:label ?label .
} 

# ORDER BY DESC(?id)